### ISSUE TITLE
Nothing with sh file

### ISSUE THREAD

**Issue by Denverledinosor** [YoCodingMonster/OpenFreezeCenter#114]
Yo,
I tried to launch on msi gf63 thin.

`cd OpenFreezeCenter/`
`./at_startup.sh`

and nothing ..
where can i see log file ?

I'm on ubuntu 22.04 btw

**Comment by Hiyajomaho-num9** [comment]
Because OpenFreezeCenter are started through konsole,and you may need to install some deps.

`os.system("konsole -e 'bash -c \"sudo python3 ${pkgdir}write_EC.py\"'")`

Try to 

> sudo apt update
sudo apt install python3-pip -y
sudo apt-get install -y konsole  python3-tk  python3-pip gir1.2-appindicator3-0.1
bash install_deps.sh
