### ISSUE TITLE
It does not do anything for the MSI GS63Vr

### ISSUE THREAD

**Issue by IvanoiuAlexandruPaul** [YoCodingMonster/OpenFreezeCenter#29]
So I use an MSI GS63VR and I install the program as you mentioned on the page but nothing happened even after I restarted the PC. I do not understand why. Can you help me please. If you have time these days I will let inside my pc so you can do it yourself and see what is going on. Maybe you will get what is going on. 
![Screenshot from 2021-06-12 20-50-54](https://user-images.githubusercontent.com/48321600/121786437-0c923580-cbc0-11eb-81f1-a78b599b5467.png)

**Comment by YoCodingMonster** [comment]
> So I use an MSI GS63VR and I install the program as you mentioned on the page but nothing happened even after I restarted the PC. I do not understand why. Can you help me please. If you have time these days I will let inside my pc so you can do it yourself and see what is going on. Maybe you will get what is going on. 
> ![Screenshot from 2021-06-12 20-50-54](https://user-images.githubusercontent.com/48321600/121786437-0c923580-cbc0-11eb-81f1-a78b599b5467.png)
> 

I will look into this matter.

I am preety sure what may have went wrong and it has something to do with install_deps.sh...
Here is errors are not handled properly and I need to manage them to run atleast all commands required before those who can or may produce errors...

Wait for the next release!! This problem should be solved👍🏻

**Comment by IvanoiuAlexandruPaul** [comment]
Thank you . Let me know when the next update is going to be released . Thank you

**Comment by Special-Niewbie** [comment]
Hello @YoCodingMonster , I have tested the app with the Ubuntu fresh installation and I can confirm that the latest version of the App doesn't do anything for the following reason:

1) The app doesn't place the file from `modprobe.d `and `modules-load.d` to the related folder system , I have checked if was missing the libs this time but the app install all of them in background.

2) I don't know if it's the reason because doesn't place well the files but I noticed that the app into the coding it miss some enabling service for the app like `usr/lib/systemd/system/openfreezcenter@.service` and the principal python file into `/usr/bin/` to let run the app in each every boot otherwise we have to boot the app on each OS Reboot. Am I right under this point?

3) Anyway, I believe it's caused of a bug from the Ubuntu system, the `io` file at really beginning simple it doesn't exist even if you choose to see the hiding file/folders into `/sys/kernel/debug/ec/ec0/io`. But a noticed that if I use `isw` it stimualte the system to create on next boot.....

I hope it's good these infos for you, and I read about your laptop situation I really feel sorry for what it happened to you ;) .

**Comment by YoCodingMonster** [comment]
> Hello @YoCodingMonster , I have tested the app with the Ubuntu fresh installation and I can confirm that the latest version of the App doesn't do anything for the following reason:
> 
> 1) The app doesn't place the file from `modprobe.d `and `modules-load.d` to the related folder system , I have checked if was missing the libs this time but the app install all of them in background.
> 
> 2) I don't know if it's the reason because doesn't place well the files but I noticed that the app into the coding it miss some enabling service for the app like `usr/lib/systemd/system/openfreezcenter@.service` and the principal python file into `/usr/bin/` to let run the app in each every boot otherwise we have to boot the app on each OS Reboot. Am I right under this point?
> 
> 3) Anyway, I believe it's caused of a bug from the Ubuntu system, the `io` file at really beginning simple it doesn't exist even if you choose to see the hiding file/folders into `/sys/kernel/debug/ec/ec0/io`. But a noticed that if I use `isw` it stimualte the system to create on next boot.....
> 
> I hope it's good these infos for you, and I read about your laptop situation I really feel sorry for what it happened to you ;) .
> 

Yes I figured that out, but currently I am without a system to write code and test on....we need to wait untill I can collect some money and be ready to buy a new one!!

**Comment by Special-Niewbie** [comment]
This it's really bad news :(

**Comment by YoCodingMonster** [comment]
> This it's really bad news :(

Yeah, I was in kids of many thing...doing multiple projects on my laptop and it then a short in my house power line and kaboom, all the appliances connected to my room breaker went vamoose...

**Comment by IvanoiuAlexandruPaul** [comment]
So sorry to hear that. Hopefully everything will be good in the end.

**Comment by fraso14** [comment]
Hey man did you solve the issue? Just try your program and had the same issue, ./at_startup does nothing
![Screenshot from 2021-08-19 17-28-07](https://user-images.githubusercontent.com/78589935/130096835-847ab330-9d6a-4492-8c59-4cf87b843c73.png)

**Comment by YoCodingMonster** [comment]
https://github.com/YoCodingMonster/OpenFreezeCenter/releases/tag/v3.1

have a look at the latest release and tell if it solved the problem or not!!
